spring:
  application:
    name: t36_cbh_505_503_sod_eod
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect 
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true           

   
  
---
#===== DEV =======
spring:
  profiles: dev
  

server:
  port: 8052
 
 
  